name: release

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v4

      - run: |
          echo "GIT_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      -
        name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: |
            ghcr.io/nikitos/tusd
          tags: |
            type=sha
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}

      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.10.0
        with:
          install: true

      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      -
        name: Build and push
        id: build
        uses: docker/build-push-action@v6
        with:
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha
          build-args: |
            GIT_VERSION=${{ env.GIT_VERSION }}
            GIT_COMMIT=${{ github.sha }}
          platforms: linux/amd64,linux/arm64/v8